export enum FileErrors {
    FILE_NOT_FOUND = 'TASK_NOT_FOUND',
    MISSING_FILE_ID = 'MISSING_TASK_ID',
    INVALID_FILE_FORMAT = 'INVALID_FILE_FORMAT',
    NO_FILE_UPLOADED = 'NO_FILE_UPLOADED',
    DATABASE_ERROR = 'DATABASE_ERROR',
    RABBITMQ_ERROR = 'RABBITMQ_ERROR',
    NO_API_KEY = "NO_API_KEY",
    INVALID_API_KEY = "INVALID_API_KEY",
    SERVER_MISCONFIG = "SERVER_MISCONFIG",
    INVALID_PAGE = 'INVALID_PAGE',
}